apiVersion: apps/v1
kind: Deployment
metadata:
  name: oshinko-oshizushi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: oshinko-oshizushi
  template:
    metadata:
      labels:
        name: oshinko-oshizushi
    spec:
      serviceAccountName: oshinko-oshizushi
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "quay.io/radanalyticsio/oshinko-oshizushi:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: "quay.io/radanalyticsio/oshinko-oshizushi:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "oshinko-oshizushi"
      volumes:
        - name: runner
          emptyDir: {}
