apiVersion: radanalytics.io/v1alpha1
kind: OshinkoJob
metadata:
  name: sparkpi
spec:
  build-type: "scala"
  git-uri: "https://github.com/radanalyticsio/s2i-integration-test-apps.git"
  app-file: "sparkpi_2.11-0.1.jar"
