apiVersion: radanalytics.io/v1alpha1
kind: OshinkoJob
metadata:
  name: sparkpi
spec:
  build-type: "python27"
  git-uri: "https://github.com/radanalyticsio/s2i-integration-test-apps.git"
  spark-options:
    - "--conf spark.driver.bindAddress=0.0.0.0"
    - "--conf spark.driver.blockManager.port=7079"
    - "--conf spark.driver.port=7078"
