apiVersion: radanalytics.io/v1alpha1
kind: OshinkoJob
metadata:
  name: sparkpi
spec:
  build-type: "java"
  git-uri: "https://github.com/radanalyticsio/s2i-integration-test-apps.git"
  app-file: "java-spark-pi-1.0-SNAPSHOT-jar-with-dependencies.jar"
