apiVersion: radanalytics.io/v1alpha1
kind: OshinkoApplication
metadata:
  name: sparkpi
spec:
  build-type: "python27"
  git-uri: "https://github.com/radanalyticsio/tutorial-sparkpi-python-flask.git"
